cc_library(
    name = "migraphx",
    srcs = [
        "lib/libmigraphx.so",
        "lib/libmigraphx_c.so",
        "lib/libmigraphx_device.so",
        "lib/libmigraphx_gpu.so",
        "lib/libmigraphx_onnx.so",
        "lib/libmigraphx_ref.so",
        "lib/libmigraphx_tf.so",
    ],
    hdrs = [
        "include/migraphx/migraphx.hpp",
    ],
    includes = [
        "include",
    ],
    visibility = ["//visibility:public"],
)
