load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")

# These must be kept up to date with the rules from tensorflow/WORKSPACE.
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "5b00383d08dd71f28503736db0500b6fb4dda47489ff5fc6bed42557c07c6ba9",
    strip_prefix = "rules_closure-308b05b2419edb5c8ee0471b67a40403df940149",
    urls = [
        "https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",  # 2019-06-13
    ],
)

# https://github.com/bazelbuild/bazel-skylib/releases
http_archive(
    name = "bazel_skylib",
    sha256 = "1c531376ac7e5a180e0237938a2536de0c54d93f5c278634818e0efc952dd56c",
    urls = [
        "https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz",
    ],
)

# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# These must be kept up to date with the rules from tensorflow/WORKSPACE.

# This should also be kept up to date with the version used by Tensorflow.
http_file(
    name = "com_github_nlohmann_json_single_header",
    sha256 = "63da6d1f22b2a7bb9e4ff7d6b255cf691a161ff49532dcc45d398a53e295835f",
    urls = [
        "https://github.com/nlohmann/json/releases/download/v3.4.0/json.hpp",
    ],
)

local_repository(
    name = "org_tensorflow",
    path = "/root/tensorflow",
)
#http_archive(
#    name = "org_tensorflow",
#    sha256 = "76abfd5045d1474500754566edd54ce4c386a1fbccf22a3a91d6832c6b7e90ad",
#    strip_prefix = "tensorflow-1.15.0",
#    urls = ["https://github.com/tensorflow/tensorflow/archive/v1.15.0.zip"],
#)

http_archive(
    name = "wtf",
    build_file = "//cc:wtf.BUILD",
    sha256 = "1837833cd159060f8bd6f6dd87edf854ed3135d07a6937b7e14b0efe70580d74",
    strip_prefix = "tracing-framework-fb639271fa3d56ed1372a792d74d257d4e0c235c",
    urls = ["https://github.com/google/tracing-framework/archive/fb639271fa3d56ed1372a792d74d257d4e0c235c.zip"],
)

load("@org_tensorflow//tensorflow:workspace3.bzl", "tf_workspace3")
tf_workspace3()

load("@org_tensorflow//tensorflow:workspace2.bzl", "tf_workspace2")
tf_workspace2()

load("@org_tensorflow//tensorflow:workspace1.bzl", "tf_workspace1")
tf_workspace1()

load("@org_tensorflow//tensorflow:workspace0.bzl", "tf_workspace0")
tf_workspace0()
